### ISSUE TITLE
Campo Fallos en Ejercicio

### ISSUE THREAD

**Issue by steveomatic** [HaritzPuerto/ProjectDBA#119]
2 Path's:

-El campo fallos cuenta el número total de fallos, independientemente de otros datos.
-El campo fallos cuenta el número de fallos del primer intento de cada usuario.

@HaritzPuerto 
@FelipeSulser 
@AlvaroFaure 

¿Qué pensáis? Escribid la respuesta

**Comment by HaritzPuerto** [comment]
Creo que debería contar solamente el número de alumnos que han fallado alguna vez. Eso ya está así implementado.

**Comment by steveomatic** [comment]
¿Por qué no contamos ambas? Más molón.

**Comment by HaritzPuerto** [comment]
ok, me parece bien

**Comment by HaritzPuerto** [comment]
¿Qué pasa con esto? ¿Se implementa ambas?
