### ISSUE TITLE
Añadir tiempo_minimo en tabla RELACIÓN del E/R

### ISSUE THREAD

**Issue by AlvaroFaure** [HaritzPuerto/ProjectDBA#120]

**Comment by HaritzPuerto** [comment]
Pues hemos hecho varias modificaciones por ahí y no se han añadido al ER... ¿Es necesario añadirlas?

**Comment by steveomatic** [comment]
Tiempo mínimo por relación está añadido desde hace tiempo. Está en el docencia2.sql.

**Comment by AlvaroFaure** [comment]
Realmente está en las modificaciones del esquema, no en docencia2. Vale, lo apunto para añadir en la wiki. Debería estar al día por si necesitamos consultar algo, supongo que lo suyo sería ir añadiéndolas.
