### ISSUE TITLE
Sinónimo de v_$session

### ISSUE THREAD

**Issue by AlvaroFaure** [HaritzPuerto/ProjectDBA#122]
Lo tenemos como:

![image](https://cloud.githubusercontent.com/assets/11488816/7548448/52ac9b2a-f609-11e4-8a3e-3e3d33015fdb.png)

y creo que puede ser el responsable de cosas como esto

![image](https://cloud.githubusercontent.com/assets/11488816/7548453/879b248c-f609-11e4-8f07-6d0250a5df8b.png)

y esto

![image](https://cloud.githubusercontent.com/assets/11488816/7548458/8e75eaf8-f609-11e4-97a4-dca3153ca63b.png)

**Comment by steveomatic** [comment]
Sí, yo tuve problemas con eso. ¿Alguien puede arrojar luz?

**Comment by FelipeSulser** [comment]
Para empezar eso da igual porque en el schema online no se pueden hacer sinónimos.
En cualquier caso le ponemos otro nombre de sinónimo como
create public synonym askhadssad for v$session;
