### ISSUE TITLE
Cambiar todos los procedures y triggers que interactúen con AUDIT_EJER

### ISSUE THREAD

**Issue by steveomatic** [HaritzPuerto/ProjectDBA#127]
Ya que se han añadido campos nuevos.

**Comment by HaritzPuerto** [comment]
Creo que ya está hecho no?

**Comment by AlvaroFaure** [comment]
Recopilo tooodo lo que interactúa con AUDIT_EJER:

PROC_ALU.sql:

![image](https://cloud.githubusercontent.com/assets/11488816/7555520/aada4eaa-f74e-11e4-839d-df5805875225.png)

ESTADISTICAS_ALU.sql:

![image](https://cloud.githubusercontent.com/assets/11488816/7555524/c20967dc-f74e-11e4-8c29-4e2445dd7415.png)

antiplagio.sql:

![image](https://cloud.githubusercontent.com/assets/11488816/7555530/d964bfb2-f74e-11e4-82e0-bb2b83dbf473.png)

**Comment by AlvaroFaure** [comment]
Como podéis ver, todo bien por aquí, así que close.
