### ISSUE TITLE
¿Para ordenar por mejores alumnos no debería ser desc?

### ISSUE THREAD

**Issue by AlvaroFaure** [HaritzPuerto/ProjectDBA#141]
@HaritzPuerto Pides que los ordene asc, ascendente, es decir, que el primero va a ser el que menos mediana tiene y va a ir creciendo hasta el último que tiene el mayor número.

Si son los mejores, ¿no debería ser al revés? Yo uso desc!

![image](https://cloud.githubusercontent.com/assets/11488816/7554138/910318b8-f71c-11e4-9b41-f62a3dcc5bf6.png)

Si me das el ok lo cambio yo en ambos sitios en mi rama.

**Comment by HaritzPuerto** [comment]
despiste mio. Debe ser desc.
