### ISSUE TITLE
Funcionamiento de mediana_alu_relacion

### ISSUE THREAD

**Issue by AlvaroFaure** [HaritzPuerto/ProjectDBA#145]
@HaritzPuerto Me tiene algo perdido tu vista.

![image](https://cloud.githubusercontent.com/assets/11488816/7554399/27954b9c-f728-11e4-9895-d2f1cb60afed.png)

Dices que te muestra la mediana de cada relación. Yo entiendo que si un usuario ha hecho dos ejercicios de la relación 1 y tres ejercicios de la relación 2 te devuelve la mediana de la relación 1 (la suma de las notas entre 2) y la mediana de la relación 2 (la suma de las notas entre 3).

Sin embargo, mira esto:

![image](https://cloud.githubusercontent.com/assets/11488816/7554405/71155596-f728-11e4-9bc5-80bc178e5913.png)

El usuario 3 (Jack Kerouac) ha hecho dos ejercicios de la relación 6 y un ejercicio de la relación 7. Entiendo que tu vista debería mostrar la mediana de Jack para la relación 7 (un 5) y la mediana para la relación 6 (un 1), pero:

![image](https://cloud.githubusercontent.com/assets/11488816/7554408/9a3abace-f728-11e4-81de-1cb70e4851b3.png)

Parece como si estuviese haciendo la media de cada alumno por asignatura.
¿Estoy entendiendo algo mal o es un error?

**Comment by AlvaroFaure** [comment]
@HaritzPuerto 
PD: En realidad yo me cargaría las vistas de las medianas por relación y me quitaría de problemas, porque cada relación es de un único alumno y no aporta mucho esa estadística.

**Comment by HaritzPuerto** [comment]
Tienes razón, la mediana por relación no aporta nada porque es única por cada estudiante. Estoy de acuerdo con borrarla
