### ISSUE TITLE
Fallo GORDO again en la vista notas_alu_por_tema

### ISSUE THREAD

**Issue by AlvaroFaure** [HaritzPuerto/ProjectDBA#146]
@HaritzPuerto Mira lo que pasa cuando llamo a tu vista:

![image](https://cloud.githubusercontent.com/assets/11488816/7554433/6365e248-f729-11e4-8ec5-14be75d93e5b.png)

Me sale una barbaridad de información y, entre ella, una repetición del usuario 1. El usuario 1 sólo ha hecho un ejercicio según mis datos: el 1 del tema 4, pero sale varias veces. El fallo gordo se debe a la siguiente tontería:

![image](https://cloud.githubusercontent.com/assets/11488816/7554485/0d4c5e94-f72b-11e4-856e-2f5dbe9b18c0.png)

Lo he cambiado y de esa forma ya es correcto. Lo commiteo en mi rama cambiándolo en docencia2 y el script.

**Comment by HaritzPuerto** [comment]
oppppssssss

**Comment by AlvaroFaure** [comment]
En tu defensa diré que yo he tardado la vida en darme cuenta xDDD
