### ISSUE TITLE
ENTREGA CAMPUS

### ISSUE THREAD

**Issue by AlvaroFaure** [HaritzPuerto/ProjectDBA#153]
http://informatica.cv.uma.es/mod/assign/view.php?id=181878

-Todo en un script
-Sin referencias a docencia O a ABD_GR_TAS
-Comentarlo bien todo
-NO comprimirlo

**Comment by AlvaroFaure** [comment]
Vamos a hacer un script como schemaUpload que condense estos ficheros (añadiendo su CREATE OR REPLACE PACKAGE ___ antes de cada CREATE OR REPLACE PACKAGE BODY ___), esto ya está en TAS, es copiar y pegar. El resto es copiar y pegar todo pero manteniéndolo ordenado.

![image](https://cloud.githubusercontent.com/assets/11488816/7584362/3d68ff1a-f89d-11e4-929f-f7149b8b47f3.png)

**Comment by AlvaroFaure** [comment]
Hago el script, lo subo y lo comentáis TODO BIEN. Y release y a tomar por saco.

Y si alguien encuentra un error, se calla (buenovaleno).

**Comment by HaritzPuerto** [comment]
Veo muchas 'y'. Ese polisíndeton es a propósito? xDDDDD
