### ISSUE TITLE
Añadir respuesta del alumno a la pregunta

### ISSUE THREAD

**Issue by HaritzPuerto** [HaritzPuerto/ProjectDBA#16]
Asignados @steveomatic y @steveomatic  así hacéis vuestro primer pull request :dancer:

**Comment by steveomatic** [comment]
Ok, perfecto.

Lo que voy a hacer es añadir la columna RESPUESTA a la tabla CALIF_EJERCICIO.
La añadiré como varchar2 del mismo tamaño que los campos enunciado y respuesta de EJERCICIO.

GOod?

**Comment by HaritzPuerto** [comment]
Perfecto @steveomatic

**Comment by steveomatic** [comment]
ya he hecho un pull request, ahora @HaritzPuerto, @AlvaroFaure y @swissmate votáis o cómo va?
