### ISSUE TITLE
Dudas script práctica 2

### ISSUE THREAD

**Issue by HaritzPuerto** [HaritzPuerto/ProjectDBA#164]
```

create tablespace TS_DOCENCIA
	datafile 'df_docencia.dat'
	size 16M
	AUTOEXTEND ON NEXT 1M ;

CREATE USER DOCENCIA IDENTIFIED BY bd 
	DEFAULT TABLESPACE TS_DOCENCIA
	QUOTA 50M ON TS_DOCENCIA;
```

El tablespace tiene 16M como mínimo y sin embargo, damos 50M a docencia. Posible es, pero... ¿es lógico?
```
create tablespace ts_index
  datafile 'ts_index.dat'
  size 30M
  AUTOEXTEND ON NEXT 1M;
```
Además, el ts_index como mínimo tiene 30M, más que ts_docencia.

**Comment by AlvaroFaure** [comment]
Claro que es lógico. Tú partes de un tablespace de 16M de tamaño y confías en que irá creciendo de tamaño mega a mega conforme se vaya llenando (pones el autoextend). Y le das a docencia su cuota de 50M, que es lo que le quieres dejar que consuma como mucho. No tiene sentido que le des a cada usuario una cuota acorde al tamaño inicial del tablespace si éste va a ir aumentando y vas a tener que ir cambiándoles la cuota uno a uno para que sea acorde al consumo. No sé si me explico.

**Comment by HaritzPuerto** [comment]
Para eso está quota unlimited no?

**Comment by AlvaroFaure** [comment]
Es que no le quieres dar cuota unlimited. Quieres que como mucho consuma 50M. A ver, es sencillo, dices: "Este tablespace es para que el usuario docencia haga lo que quiera sobre él. Voy a poner que empiece con un tamaño 16M y docencia va a ir haciendo sus cosas. Y conforme vaya haciendo sus cosas, va a ir aumentando el tamaño mega a mega, y él no va a tener problemas. Pero le voy a poner un límite, sólo va a poder usar ese tablespace hasta 50M".

¿Qué pasa si pones la cuota menor que el primer tamaño del tablespace? Pues que va a ir haciendo cosas sobre la DB y va a ir aumentando el tablespace pero al llegar a ese tamaño (muy pequeño) que le has puesto, se acabó. ¿Qué pasa si se lo pones unlimited? Pues que va a poder seguir haciendo cosas hasta que se acabe tu memoria del sistema. Piensa que tienes el autoextend, no le estás dando 50M en un tablespace de 16M, le estás dando 50M en un tablespace de mínimo 16M.

**Comment by HaritzPuerto** [comment]
ok, I got it
