### ISSUE TITLE
Crear procedimiento para matar sesión

### ISSUE THREAD

**Issue by HaritzPuerto** [HaritzPuerto/ProjectDBA#23]

**Comment by steveomatic** [comment]
Ya lo hice, pero no he podido probarlo, mi sql developer esta cascao. En el drive está.

**Comment by HaritzPuerto** [comment]
No me funciona

**Comment by steveomatic** [comment]
@HaritzPuerto lee este commit:

Arregladas comillas
ya funciona (consegui matar un usuario en mi bd con esa procedure) PERO HAY UN PROBLEMA

no sabemos como hacer bien lo de que se pueda leer de v_$session. En mi caso si me ha funcionado todo ok porque ME DI PERMISO DE SYSDBA SOBRE ESA TABLA EXPLICITAMENTEEEEEEEEEEEEEE
felipe propone crear un SYNONYM PUBLICO tal y como ha hecho en su commit, pero A MI NO ME FUNCIONA, pruebalo hartiz plz

**Comment by HaritzPuerto** [comment]
A mi sí me funciona lo que ha hecho felipe. Has hecho grant select on v_$session to docencia;? Eso no viene en el script de felipe

**Comment by steveomatic** [comment]
claro tio
pero no importa, si ya os va a los dos, sera fallo de algo raro de mi bd (recuerda que tengo una de oracle propia...)

si has comprobado que ya va lo que cambie de las comillas, pull request

**Comment by HaritzPuerto** [comment]
Lo comenté en PR, pero lo pongo tamibén aquí


Me sale el siguiente error:
Informe de error:
ORA-00026: falta el identificador de sesión o no es válido
ORA-06512: en "DOCENCIA.GEST_USUARIO", línea 94
ORA-06512: en línea 1
00026. 00000 - "missing or invalid session ID"
*Cause: Missing or invalid session ID string for ALTER SYSTEM KILL SESSION.
*Action: Retry with a valid session ID.
@steveomatic

**Comment by steveomatic** [comment]
@HaritzPuerto 
le he añadido las excepciones
¿Puedes probarlo y decirme que EXCEPCION te da?
Si no te da ninguna, es porque falla al intentar acceder al synonym

**Comment by HaritzPuerto** [comment]
@steveomatic  voy

**Comment by steveomatic** [comment]
@HaritzPuerto fijate que estes usando el ultimo commit que lo hice hace un minuto xDDDD

**Comment by HaritzPuerto** [comment]
@steveomatic Mata la sesión correctamente pero si le doy un usuario que no existe no me dice nada
