### ISSUE TITLE
Pensar extensiones del módulo

### ISSUE THREAD

**Issue by HaritzPuerto** [HaritzPuerto/ProjectDBA#28]
@steveomatic @FelipeSulser @AlvaroFaure @HaritzPuerto
Para el próximo día

**Comment by HaritzPuerto** [comment]
Crear función que dé los ejercicios más fallados por los alumnos (los más "difíciles").
Dar el tiempo que dedica cada alumno a cada relación y a cada tema.
Dar los mejores alumnos por tema, por relación.
Hacer una función que nos dé una lista con los alumnos más completos (los que mejor lo han hecho de media en todos los temas y en todas las relaciones).

**Comment by HaritzPuerto** [comment]
No os olvidéis de esto @steveomatic @FelipeSulser @AlvaroFaure 
Fecha límite: miércoles!

**Comment by steveomatic** [comment]
Sistema de dedicación por usuario o grupo de usuarios

**Comment by steveomatic** [comment]
Sistema de plagio sencillo (aka comprobar que un usuario no acierta todas las preguntas en menos de 5 minutos sin fallar nunca)

**Comment by steveomatic** [comment]
Matriz de covarianzas para medir la dispersión entre dos o más variables
(por ejemplo, ver la relación entre relación y ejercicios en función de la dificultad)

**Comment by HaritzPuerto** [comment]
Co,mentariios profe: lpad oracle, palabras claves en cada ejercicio, 

añadir tiempo estimado por relación para antiplagio, 

correlaciónn oracle. Cómo incide un parámetro en otro. la nota de un ejer respecto a la nota final.
