### ISSUE TITLE
Permisos para el procedimiento MATAR_SESION

### ISSUE THREAD

**Issue by steveomatic** [HaritzPuerto/ProjectDBA#31]
Parece ser que es necesario que sys (no system) le de permiso explícito al usuario creador del procedimiento sobre la vista v$session.

Ask professor.

**Comment by HaritzPuerto** [comment]
Ni system lo puede ejecutar LOL

**Comment by steveomatic** [comment]
10:13: Hola,
somos del grupo TAS de Administración de Bases de Datos (3º).

Tenemos una duda en cuanto al procedimiento para matar una sesión. Para acceder a la vista v$session desde un procedimiento, parece que sys (ni siquiera system) tiene que darle permiso explícito al usuario que esté creando el procedimiento.
¿Podemos incluir esto o hay otra forma de hacerlo?

El procedimiento lo hemos hecho como sigue:
http://pastebin.com/Y5vj9pWd

Gracias por tu tiempo,
grupo TAS.
viernes, 17 de abril de 2015
08:18: Lo estáis haciendo en la máquina virtual imagino. Lo digo porque veréis que si se hace en el servidor no funciona ese acceso porque no tenéis permiso a ver esas vistas.

Revisad los permisos que tiene ese usuario desde el que estáis accediendo y veréis que algo le habéis dado que no tiene el vuestro del servidor. 

-----------------------------

Creo que no se ha leído ni la pregunta ni el código, pero me da la sensación que es la forma de hacerlo, ya que no lo ha contraindicado.

**Comment by steveomatic** [comment]
@HaritzPuerto lee este commit:

Arregladas comillas
ya funciona (consegui matar un usuario en mi bd con esa procedure) PERO HAY UN PROBLEMA

no sabemos como hacer bien lo de que se pueda leer de v_$session. En mi caso si me ha funcionado todo ok porque ME DI PERMISO DE SYSDBA SOBRE ESA TABLA EXPLICITAMENTEEEEEEEEEEEEEE
felipe propone crear un SYNONYM PUBLICO tal y como ha hecho en su commit, pero  A MI NO ME FUNCIONA, pruebalo hartiz plz
