### ISSUE TITLE
Controlar las excepciones de las funciones ya creadas

### ISSUE THREAD

**Issue by HaritzPuerto** [HaritzPuerto/ProjectDBA#33]

**Comment by FelipeSulser** [comment]
procedo a controlar las excepciones "others" en cada procedure del paquete GEST_USUARIO.

Más adelante crearé excepciones propias para controlar específicamente

**Comment by HaritzPuerto** [comment]
¿Cómo podemos controlar las excepciones por no tener privilegios?
http://docs.oracle.com/cd/B10501_01/appdev.920/a96624/07_errs.htm#784 Aquí no hay nada.
