### ISSUE TITLE
Sequence para faure en procedimiento "crear n usuarios"

### ISSUE THREAD

**Issue by FelipeSulser** [HaritzPuerto/ProjectDBA#34]
@AlvaroFaure Te adjunto lo que he hecho para que lo veas.

ANTERIORMENTE DOCENCIA DEBE CREAR SEQUENCE ( o system, pero si lo hace docencia darle grant create sequence).
create sequence SEQ_CREA_USUARIOS start with 1 increment by 1;

AHORA VIENE EL BODY DEL PROCEDURE( Falta agregar el usuario a la tabla usuarios):

/**
*PRECOND: Tener creada sequence seq_crea_usuarios
*Crea n usuarios y se les asigna a la asignatura "asignatura"
*/
 PROCEDURE CREAR_USUARIOS(asignatura IN VARCHAR2, numero IN NUMBER) IS 
  VAR_COUNTER number(6) ;
  n pls_integer;
  BEGIN
  VAR_COUNTER := 0;
  	FOR VAR_COUNTER IN 1..numero 
  	LOOP 
      n := seq_crea_usuarios.NEXTVAL;
	    EXECUTE IMMEDIATE 'CREATE USER ' || asignatura || '_'||n||    ' IDENTIFIED BY ' || asignatura||'_'||n;
	    SYS.dbms_output.put_line('Usuario '|| ' creado correctamente');
	    END LOOP;
  END CREAR_USUARIOS;

**Comment by AlvaroFaure** [comment]
Voy a hacerlo como ha dicho el profesor. Ya he estado trabajando en ello con la cadena de string alfanumérico a ver si consigo hacerlo bien.
