### ISSUE TITLE
Dudas para el lab del miércoles 22

### ISSUE THREAD

**Issue by HaritzPuerto** [HaritzPuerto/ProjectDBA#37]
FOR var_usuario in c_usuarios LOOP -- Puedo declarar la variable var_usuario aquí.
    -- llamar a BORRAR_USUARIO(nombre); -- SI NO HAY USUARIOS QUÉ PASA??
  END LOOP;

¿Cómo llamar a otra función?
¿Cómo manejar que no haya usuarios? el cursor se instancia en el loop.

**Comment by FelipeSulser** [comment]
¿Cómo usar los cursores para ejecutar una sentencia SQL y comparar resultados?
En otras palabras, teniendo en dos cursores el contenido de dos queries, cómo se comparan?
No se el nombre de las columnas ya que puede ser cualquier tablas.

**Comment by HaritzPuerto** [comment]
execute immediate ... into var using
NO usar cursores

**Comment by steveomatic** [comment]
Utilizar la librería lpad para las estadísticas

**Comment by FelipeSulser** [comment]
@HaritzPuerto Pero eso solo sirve para single column queries.
http://docs.oracle.com/cd/B12037_01/appdev.101/b10807/13_elems017.htm
Si lo que quiero es select * from dba_users; el Into del execute immediate no va. Ya que tengo muchas columnas

**Comment by HaritzPuerto** [comment]
@FelipeSulser el profe nos dijo que no usáramos cursores para comparar. Haces el minus y disjunction y si no hay data genial está bien, si hay data, entonces no está bien la respuesta. Creo que era así. @steveomatic @AlvaroFaure  tal vez lo pueda explicar mejor

**Comment by FelipeSulser** [comment]
Sisi, no te preocupes. Creo que ya he llegado a la solución del problema. (Está en la branch PaqueteCorrecEjer).
