### ISSUE TITLE
Cambios sobre E/R (ACUMULAR CAMBIOS AQUÍ)

### ISSUE THREAD

**Issue by steveomatic** [HaritzPuerto/ProjectDBA#44]
Hay que añadir atributos para tratar el tema del TIEMPO:

- fecha de apertura absoluta en EJERCICIO para el modo "Quién lo termina antes desde que se abrió" 
  fecha_apertura DATE
- fecha de entrega absoluta en CALIF_EJERCICIO para ambos modos.
  fecha_entrega DATE
- fecha de "recogida" del ejercicio en CALIF_EJERCICIO, para poder hacer el modo cronómetro

Todos los cambios se acumulan aqui

**Comment by FelipeSulser** [comment]
Yo pondría que en usuario, el nombre sea unique ( ya que en la base de datos lo ha de ser).

**Comment by AlvaroFaure** [comment]
Lo apunto en la wiki para cambiarlo todo junto.
