### ISSUE TITLE
Delete FK

### ISSUE THREAD

**Issue by HaritzPuerto** [HaritzPuerto/ProjectDBA#51]
¿Cómo se hace eso?
DELETE FROM usuario where usuario_id = 1 CASCADE; No va
DELETE FROM usuario where usuario_id = 1 ON CASCADE; Tmp
DELETE FROM usuario where usuario_id = 1 CASCADE CONSTRAINTS; TAMPOCO

He encontrado esto:
ALTER TABLE public.pref_scores
DROP CONSTRAINT pref_scores_gid_fkey,
ADD CONSTRAINT pref_scores_gid_fkey
   FOREIGN KEY (gid)
   REFERENCES pref_games(gid)
   ON DELETE CASCADE; -- ohh yeah

Sabéis qué significa no? Creo que hay que añadir eso en todas las FK.
@steveomatic @FelipeSulser @AlvaroFaure

**Comment by FelipeSulser** [comment]
tienes razón, si se borra el usuario deberíamos borrar todas sus instancias de preguntas etc. Otra opción sería no borrar de la tabla al usuario( es decir, que nunca se elimine).

**Comment by HaritzPuerto** [comment]
Si se borra el usuario, se debería borrar de la tabla, si no, podráimos crear un usuario con el mismo nombre pero no introducirlo en la tabla...
