### ISSUE TITLE
Aumentar tamaño de nombre en USUARIO de 10 a 20

### ISSUE THREAD

**Issue by AlvaroFaure** [HaritzPuerto/ProjectDBA#55]

**Comment by FelipeSulser** [comment]
En oracle el max es 30.
http://docs.oracle.com/cd/E11882_01/server.112/e41084/sql_elements008.htm#SQLRF51129

**Comment by AlvaroFaure** [comment]
Que sea 30.

**Comment by steveomatic** [comment]
Pon esto en el issue de CAMBIOS SOBRE EL E/R y asi lo acumulamos todo
igual con el otro, para que no haya lio

**Comment by AlvaroFaure** [comment]
Ah, cierto, también hay que cambiarlo allí. Lo añado ahora mismo.

**Comment by steveomatic** [comment]
Easy, cierra este y el otro cuando no te haga falta

**Comment by AlvaroFaure** [comment]
Revisa y mergea mis ramas, y sí, yo los voy cerrando. Pero no puedo cerrar hasta que no mergees mis PR.
