### ISSUE TITLE
Duda usuario responde un código sql no válido

### ISSUE THREAD

**Issue by HaritzPuerto** [HaritzPuerto/ProjectDBA#65]
BEGIN
  --mete la query del usuario
    select respuesta
    into v_alu_query
    from CALIF_EJERCICIO
    where usuario_usuario_id = cor_usuario_id AND relacion_relacion_id = cor_relacion_id AND asignatura_id = cor_asignatura_id AND ejercicio_ejercicio_id = cor_ejercicio_id;
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE = -01789 then RAISE ERROR_COLUMNAS_DIF; -- Este error se puede dar cuando hacemos select a,b from.. union select a from.. Esto causa un error ya que hace la unión de columnas diferentes.
        ELSIF SQLCODE = -01403 then RAISE ERROR_NO_DATOS;
        ELSIF SQLCODE = -00942 then RAISE ERROR_TABLA_NO_EXISTE;
        ELSE RAISE ERROR_DESCONOCIDO; -- DUDA AQUÍ. Este error también podría ser que el alumno hubiera escrito una solución que no fuese un código sql válido. ES ESTO CORRECTO?
        END IF;
  END;

He comentado en el código la duda
@steveomatic @FelipeSulser

**Comment by steveomatic** [comment]
@HaritzPuerto  la primera duda no la entiendo, al usuario que esta probando si su ejercicio esta bien o no, TIENE que tener el mismo numero de filas y columnas, por tanto si hay diferencia en el numero de columnas esta mal directamente. no?
 
@HaritzPuerto  el segundo error tienes razón, acabo de probarlo. Lo que voy a hacer es añadir como output: 
WHEN ERROR_DESCONOCIDO THEN DBMS_OUTPUT.PUT_LINE('Comando o error desconocido');

y listo

**Comment by HaritzPuerto** [comment]
@steveomatic en el caso 1 solo estaba comentando el por qué de eso. Cuando lo vi por primera vez no sabía a qué se refería. La duda era el segundo comentario. Debí haberlo indicado xP

**Comment by HaritzPuerto** [comment]
ya está arregaldo
