### ISSUE TITLE
No se puede introducir respuestas con ; (ni el alumno ni el profesor)

### ISSUE THREAD

**Issue by HaritzPuerto** [HaritzPuerto/ProjectDBA#67]
En el dataset que tenía al principio todas las respuestas las tenía con ; esto implica que en la corrección se ejecutaría:

     select count(*) from (SELECT SYSDATE FROM DUAL; MINUS SELECT sysdate FROM dual;);

Esto obviamente da un problema. La SOLUCIÓN es quitar los ;

Pregunta:

Obligamos a los usuarios a no poner ; o los quitamos nosotros?

@steveomatic @FelipeSulser @AlvaroFaure

**Comment by steveomatic** [comment]
@HaritzPuerto 
Yo pienso que lo mejor es hacer un pequeño parser que mire si el ultimo caracter (que no sea end of line o space) es un punto y coma, y en caso de serlo, quitarlo.

**Comment by HaritzPuerto** [comment]
@steveomatic gracias por ofrecerte voluntario a hacer un parser no sé cómo xDDDD
ahora en serio, cómo se haría eso?? Hay alguna manera de eliminar el último carácter si es ; en plsql de forma similar a JAVA?

**Comment by steveomatic** [comment]
Voy a ello :DDDDDDDDDDDDDDDDD

**Comment by HaritzPuerto** [comment]
Acabo de leer el "parser" y me parece correcto, no lo he probado aún, pero tiene buena pinta, fallaría si la respuesta es "select x from dual;        ". Deberíamos preguntarle al profesor.
