### ISSUE TITLE
Bug si salta un error al corregir las tablas no pone un 0 en la respuesta

### ISSUE THREAD

**Issue by HaritzPuerto** [HaritzPuerto/ProjectDBA#68]
select count(*) from (SELECT SYSDATE || 'hola' FROM DUAL MINUS SELECT SYSDATE FROM DUaL);

solución: select sysdate from dual

respuestar alu: select sysdate ''hola'' from dual

el select count(*) no funciona y eso hace que ponga incorrecto pero no se le ponga un 0 en el ejercicio

**Comment by steveomatic** [comment]
Lo que hay que hacer es que SEA CUAL SEA EL ERROR HAY QUE PONERLE UN 0 AL ALUMNO
yo me encargo

**Comment by steveomatic** [comment]
@HaritzPuerto 
@FelipeSulser 
@AlvaroFaure 
lo que voy a hacer va a ser crear una nueva procedure que sea para cambiar la nota, que si no es un lio.

**Comment by HaritzPuerto** [comment]
eso ya está hecho!!

**Comment by steveomatic** [comment]
LOL TIO

ya lo habia hecho, miro para hacer un branch, y veo que lo tenias hecho xd

**Comment by steveomatic** [comment]
Closeo.
