### ISSUE TITLE
Tiempo que dedica cada alumno a cada relación y a cada tema. 

### ISSUE THREAD

**Issue by HaritzPuerto** [HaritzPuerto/ProjectDBA#75]
Dar el tiempo que dedica cada alumno a cada relación y a cada tema.

**Comment by steveomatic** [comment]
lol at @AlvaroFaure cambiando el título por una mayúscula

**Comment by AlvaroFaure** [comment]
Lo dices como si no me conocieses.
![6abbi](https://cloud.githubusercontent.com/assets/11488816/7433802/5a529016-f035-11e4-8573-e6d5a7d3e3be.jpg)

**Comment by HaritzPuerto** [comment]
Había copypasteado xDDDD

**Comment by steveomatic** [comment]
hahahahahahahahaahaha @AlvaroFaure

**Comment by steveomatic** [comment]
se va a hacer solo por relacion y no por tema
