### ISSUE TITLE
Modificar parser 

### ISSUE THREAD

**Issue by HaritzPuerto** [HaritzPuerto/ProjectDBA#85]
Usar replace ;

**Comment by steveomatic** [comment]
@HaritzPuerto un replace de todas las ; ?
yo entendí que con mirar el último carácter estaba de sobra
@FelipeSulser que dijo el profesor sobre4 esto?

**Comment by AlvaroFaure** [comment]
Yo recuerdo lo del último carácter. Dijo que supondríamos que no va a enviar la pregunta con nada después, que si no es mucho lío.

**Comment by FelipeSulser** [comment]
reemplaza todas las ;

Eso es lo que dijo.

**Comment by steveomatic** [comment]
yo recuerdo también lo del último carácter, diciendo que así suavizábamos una parte de los fallos que pueden cometer los alumnos. En cambio, en lo otro dijo que era cierto que no, que la consulta podía tener ;  por ahí.

**Comment by FelipeSulser** [comment]
Pero dijo que eso es un detalle muy pequeño.
A mi me quedó muy claro que lo que quería es un REPLACE de todo

**Comment by steveomatic** [comment]
Bueno, pues más easy. Luego lo hago.
