### ISSUE TITLE
@alvaroFaure's RAMA

### ISSUE THREAD

**Issue by FelipeSulser** [HaritzPuerto/ProjectDBA#87]
@AlvaroFaure tienes que cambiar las siguientes cosas:

Es grant R_ALUMNO ( no R_USUARIO).

El código de SQLCODE para controlar el error de que el rol no existe es -1919 en vez de -1921

**Comment by AlvaroFaure** [comment]
Gracias por revisarlo. Ya lo he arreglado y he hecho commit. Si no hay nada más que arreglar se puede mergear entonces.
