### ISSUE TITLE
Comentarios sobre desarrollo de SW

### ISSUE THREAD

**Issue by HaritzPuerto** [HaritzPuerto/ProjectDBA#91]
ERROR_PRIVS_INSUF exception;    --Privilegios insuficientes
  ERROR_USUARIO_EXISTE exception; --Usuario no existe
  ERROR_ROL_NO_EXISTE exception;  --Rol no existe
  ERROR_UK_VIOLADA exception;     --Clave única violada
  ERROR_DESCONOCIDO exception;    --Otro error
  
  --BEGIN del procedimiento
  BEGIN

Este tipo de comentarios generalmente son una MALA PRÁCTICA. El código es lo suficientemente autoexplicativo como para poner comentarios xD
Hay que hacer el código claro y poner comentarios donde realmente hagan falta.

Obviamente no hay que borrarlos, es solo información.

**Comment by steveomatic** [comment]
Lol

**Comment by AlvaroFaure** [comment]
Si me señalas sólo ese BEGIN parece que soy gilipollas poniendo «BEGIN del procedimiento» como si no supiésemos lo que es un BEGIN, pero es que como hay varios BEGIN encadenados voy señalando cuál es cada uno para no perderse si se viene a modificar algo rápido del código. Recordemos que el examen es dentro de dos semanas. Lo de las excepciones sí es redundante, porque el nombre es explicativo. Me lo ahorraré de ahora en adelante.

**Comment by AlvaroFaure** [comment]
De todas formas, podrías habérmelo dicho ayer cuando te enseñé mis comentarios en la práctica de Robots, que son así. Te los enseñaba para que me dijeses si te parecía bien, pero como dijiste que «no te interesaba, es de otra asignatura» pues los hice igual. Podría haberme ahorrado bastante tiempo perdido.
