### ISSUE TITLE
Crear usuario: creas el usuario y no se inserta en la tabla

### ISSUE THREAD

**Issue by HaritzPuerto** [HaritzPuerto/ProjectDBA#92]
WHEN ERROR_UK_VIOLADA THEN DBMS_OUTPUT.put_line('Error: usuario ' || usuario || ' creado pero el nombre está repetido y debe ser único');

Según eso, puedes crear un usuario y luego no insertarlo en la tabla, WTF?! Se crea el usuario sii se inserta en la tabla.

**Comment by HaritzPuerto** [comment]
--PRECONDICION: HA DE ESTAR CREADA LA SECUENCIA usuario_seq
PROCEDURE CREAR_USUARIO(usuario IN VARCHAR2, pass IN VARCHAR2) IS 
  
  --Declaración de las excepciones propias
  ERROR_PRIVS_INSUF exception;    --Privilegios insuficientes
  ERROR_USUARIO_EXISTE exception; --Usuario no existe
  ERROR_ROL_NO_EXISTE exception;  --Rol no existe
  ERROR_UK_VIOLADA exception;     --Clave única violada
  ERROR_DESCONOCIDO exception;    --Otro error
  
  --BEGIN del procedimiento
  BEGIN
  
    --BEGIN del CREATE USER
    BEGIN
      EXECUTE IMMEDIATE 'CREATE USER ' || usuario || ' IDENTIFIED BY ' || pass;
      --DBMS_OUTPUT.PUT_LINE('CREATE USER ' || usuario || ' IDENTIFIED BY ' || pass);
      DBMS_OUTPUT.PUT_LINE('Usuario ' || usuario || ' creado correctamente');   
      
      --Excepciones del CREATE USER
      EXCEPTION WHEN OTHERS THEN 
      IF SQLCODE = -1031 then raise ERROR_PRIVS_INSUF;
      ELSIF SQLCODE = -1920 then raise ERROR_USUARIO_EXISTE;
      ELSE RAISE ERROR_DESCONOCIDO;
      END IF;
    END;
    
    --BEGIN del INSERT INTO USUARIO
    BEGIN
      INSERT INTO USUARIO VALUES(usuario_seq.NEXTVAl,usuario);
      COMMIT;
      
      --Excepciones del INSERT INTO USUARIO
      EXCEPTION WHEN OTHERS THEN 
      IF SQLCODE = -1031 then raise ERROR_PRIVS_INSUF;
      ELSIF SQLCODE = -00001 then raise ERROR_UK_VIOLADA;
      ELSE raise ERROR_DESCONOCIDO;
      END IF;
    END;
    
    --BEGIN DEL GRANT R_ALUMNO
    BEGIN
      EXECUTE IMMEDIATE 'GRANT R_ALUMNO TO ' || usuario;
      --DBMS_OUTPUT.PUT_LINE('GRANT R_ALUMNO TO ' || usuario);
      
      --Excepciones del GRANT R_ALUMNO
      EXCEPTION WHEN OTHERS THEN 
      IF SQLCODE = -1031 then raise ERROR_PRIVS_INSUF;
      ELSIF SQLCODE = -1920 then raise ERROR_USUARIO_EXISTE;
      ELSIF SQLCODE = -1919 then raise ERROR_ROL_NO_EXISTE;
      ELSE raise ERROR_DESCONOCIDO;
      END IF;
    END;
    
    EXCEPTION
    WHEN ERROR_PRIVS_INSUF THEN DBMS_OUTPUT.put_line('Error: no se tienen privilegios suficientes');
    WHEN ERROR_USUARIO_EXISTE THEN DBMS_OUTPUT.put_line('Error: el usuario ' || usuario || ' ya existe');
    WHEN ERROR_UK_VIOLADA THEN DBMS_OUTPUT.put_line('Error: usuario ' || usuario || ' creado pero el nombre está repetido y debe ser único');
    WHEN ERROR_ROL_NO_EXISTE THEN DBMS_OUTPUT.put_line('Error: El rol R_ALUMNO no existe');
    WHEN ERROR_DESCONOCIDO THEN DBMS_OUTPUT.put_line('Error desconocido');
  END CREAR_USUARIO; 


Creo que debería ser así (confirmadme): 
--PRECONDICION: HA DE ESTAR CREADA LA SECUENCIA usuario_seq
PROCEDURE CREAR_USUARIO(usuario IN VARCHAR2, pass IN VARCHAR2) IS 
  
  --Declaración de las excepciones propias
  ERROR_PRIVS_INSUF exception;    --Privilegios insuficientes
  ERROR_USUARIO_EXISTE exception; --Usuario no existe
  ERROR_ROL_NO_EXISTE exception;  --Rol no existe
  ERROR_UK_VIOLADA exception;     --Clave única violada
  ERROR_DESCONOCIDO exception;    --Otro error
  
  --BEGIN del procedimiento
  BEGIN
  

      EXECUTE IMMEDIATE 'CREATE USER ' || usuario || ' IDENTIFIED BY ' || pass;
      --DBMS_OUTPUT.PUT_LINE('CREATE USER ' || usuario || ' IDENTIFIED BY ' || pass);
      DBMS_OUTPUT.PUT_LINE('Usuario ' || usuario || ' creado correctamente');   
      
      --Excepciones del CREATE USER
      EXCEPTION WHEN OTHERS THEN 
      IF SQLCODE = -1031 then raise ERROR_PRIVS_INSUF;
      ELSIF SQLCODE = -1920 then raise ERROR_USUARIO_EXISTE;
      ELSE RAISE ERROR_DESCONOCIDO;
      END IF;

    

      INSERT INTO USUARIO VALUES(usuario_seq.NEXTVAl,usuario);
      COMMIT;
      
      --Excepciones del INSERT INTO USUARIO
      EXCEPTION WHEN OTHERS THEN 
      IF SQLCODE = -1031 then raise ERROR_PRIVS_INSUF;
      ELSIF SQLCODE = -00001 then raise ERROR_UK_VIOLADA;
      ELSE raise ERROR_DESCONOCIDO;
      END IF;

    

      EXECUTE IMMEDIATE 'GRANT R_ALUMNO TO ' || usuario;
      --DBMS_OUTPUT.PUT_LINE('GRANT R_ALUMNO TO ' || usuario);
      
      --Excepciones del GRANT R_ALUMNO
      EXCEPTION WHEN OTHERS THEN 
      IF SQLCODE = -1031 then raise ERROR_PRIVS_INSUF;
      ELSIF SQLCODE = -1920 then raise ERROR_USUARIO_EXISTE;
      ELSIF SQLCODE = -1919 then raise ERROR_ROL_NO_EXISTE;
      ELSE raise ERROR_DESCONOCIDO;
      END IF;

    
    EXCEPTION
    WHEN ERROR_PRIVS_INSUF THEN DBMS_OUTPUT.put_line('Error: no se tienen privilegios suficientes');
    WHEN ERROR_USUARIO_EXISTE THEN DBMS_OUTPUT.put_line('Error: el usuario ' || usuario || ' ya existe');
    WHEN ERROR_UK_VIOLADA THEN DBMS_OUTPUT.put_line('Error: usuario ' || usuario || ' creado pero el nombre está repetido y debe ser único');
    WHEN ERROR_ROL_NO_EXISTE THEN DBMS_OUTPUT.put_line('Error: El rol R_ALUMNO no existe');
    WHEN ERROR_DESCONOCIDO THEN DBMS_OUTPUT.put_line('Error desconocido');
  END CREAR_USUARIO;

**Comment by AlvaroFaure** [comment]
Resumo el follón por aquí para que quede constancia: Mi commit es el procedures.sql de la master pero comentado y organizado. Lo que falla aquí, falla allí, y lo que falla en ambos es que, dado que el CREATE USER tiene un commit implícito y del INSERT hacemos commit (nos lo dijo el profesor), si el insert o el grant fallan, el usuario se ha creado o el usuario se ha creado y además insertado.

Ahora surgen dos formas de verlo:

Haritz considera que toda la función ha de funcionar como una transacción, y si alguna de las tres partes falla, debería revertirse todo lo que se ha hecho antes. Para ello, la única solución es regular cada excepción posible y tener en cuenta en qué rama se ha dado (es decir, para el caso de la excepción de privilegios insuficientes, crear tres excepciones: privs_create, privs_insert, privs_role) y al final de la función, según cuál de las excepciones ha sido, hacer drop user, drop user y delete from usuario o sólo avisar del error.

Por mi parte, opino que aunque me encantaría que las funciones funcionasen como transacciones, es un follón de implementar, porque prácticamente para cada procedimiento habría que tener esto en cuenta y trabajar con bastantes excepciones en cada función y con lo que hay que hacer para cada una, cuando en realidad no lo veo tan necesario porque la única forma de que el insert falle es que trate de añadir en la tabla usuario un nombre que ya está en la tabla. 

Esto sólo puede ocurrir si antes se ha insertado A MANO (con insert into a pelo) ese nombre (no que se creen dos usuarios con mismo nombre, porque ya habría saltado la excepción del create) y la única posibilidad de que el grant role falle es que alguien borre A MANO el role R_ALUMNO.

Opino que me encantaría tener totalmente cubierto eso y asegurar que todo se ejecuta atómicamente pero dado lo improbable de que se produzca algún error en medio del proceso creo que tomarse el trabajo que requiere asegurar la transacción no merece la pena.

Pero lo dejo aquí para que entre todos decidamos.

**Comment by HaritzPuerto** [comment]
Esta tarde voy a intentar hacerlo

**Comment by HaritzPuerto** [comment]
Ya está... Ni 10 minutos...

**Comment by HaritzPuerto** [comment]
En Borrar usuario también pasa, voy a ello

**Comment by HaritzPuerto** [comment]
Al hacer un delete de la tabla usuario se trata la excpetion         IF SQLCODE = -01918 then RAISE ERROR_USUARIO_NO_EXISTE;
wtf?! voy a ello
